
#Machine Energy Usage Config. This config is synced from server to client.
[usage]
	#Energy per operation tick (Joules).
	enrichmentChamber = "500"
	#Energy per operation tick (Joules).
	osmiumCompressor = "1000"
	#Energy per operation tick (Joules).
	combiner = "500"
	#Energy per operation tick (Joules).
	crusher = "500"
	#Energy per operation tick (Joules).
	metallurgicInfuser = "500"
	#Energy per operation tick (Joules).
	purificationChamber = "2000"
	#Energy per operation tick (Joules).
	energizedSmelter = "500"
	#Energy per operation tick (Joules).
	digitalMiner = "2500"
	#Energy per operation tick (Joules).
	electricPump = "1000"
	#Energy that can be transferred at once per charge operation (Joules).
	chargePad = "1024000"
	#Energy per operation tick (Joules).
	rotaryCondensentrator = "500"
	#Energy per operation tick (Joules).
	oxidationChamber = "2000"
	#Energy per operation tick (Joules).
	chemicalInfuser = "2000"
	#Energy per operation tick (Joules).
	chemicalInjectionChamber = "4000"
	#Energy per operation tick (Joules).
	precisionSawmill = "500"
	#Energy per operation tick (Joules).
	chemicalDissolutionChamber = "4000"
	#Energy per operation tick (Joules).
	chemicalWasher = "200"
	#Energy per operation tick (Joules).
	chemicalCrystallizer = "4000"
	#Energy per operation tick (Joules).
	seismicVibrator = "5000"
	#Energy per operation tick (Joules).
	pressurizedReactionBase = "500"
	#Energy per operation tick (Joules).
	fluidicPlenisher = "1000"
	#Energy per operation tick (Joules).
	laser = "100000"
	#Energy per operation tick (Joules).
	formulaicAssemblicator = "1000"
	#Energy per operation tick (Joules).
	modificationStation = "1000"
	#Energy per operation tick (Joules).
	isotopicCentrifuge = "2000"
	#Energy per operation tick (Joules).
	nutritionalLiquifier = "2000"
	#Energy per operation tick (Joules).
	antiprotonicNucleosynthesizer = "100000"
	#Energy per operation tick (Joules).
	pigmentExtractor = "2000"
	#Energy per operation tick (Joules).
	pigmentMixer = "2000"
	#Energy per operation tick (Joules).
	paintingMachine = "1000"
	#Energy per chunk per tick (Joules).
	dimensionalStabilizer = "5000"

	#Teleporter
	[usage.teleporter]
		#Base Joules cost for a teleportation.
		teleporterBase = "1000"
		#Joules per unit of distance travelled during teleportation - sqrt(xDiff^2 + yDiff^2 + zDiff^2).
		teleporterDistance = "10"
		#Flat additional cost for interdimensional teleportation.
		teleporterDimensionPenalty = "10000"

